### ISSUE TITLE
Hide subprojects from Malta

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-backend#115]
Currently, all subprojects in Malta and shown on the map and in the search results: 5376 instead of 120.
This is a regression due to the materialisation of the instance of -> subclass hierarchy.

**Comment by D063520** [comment]
This should be fixed in the next indexing cycle

**Comment by madewild** [comment]
On https://kohesio.development.ec.europa.eu/ it's still wrong. Or do you mean tomorrow?

**Comment by madewild** [comment]
@D063520 we still have 5376 MT projects on https://kohesio.development.ec.europa.eu/ this morning...

**Comment by D063520** [comment]
this is "normal"
so basically test is the frozen index .... we are currently not updating it .... the last one is from Friday.
I can change it in the live endpoint if you want?

**Comment by madewild** [comment]
My point is, it's also wrong on the live endpoint: https://kohesio.development.ec.europa.eu/

**Comment by madewild** [comment]
OK let's move the frozen index to test tomorrow and check.

**Comment by madewild** [comment]
Working on https://kohesio.test.ec.europa.eu/
